//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PFlowSpeed.rc
//
#define IDS_PLUGINDESCRIPTION           1
#define IDS_PARAMETERS                  2
#define IDS_EMITSTART                   3
#define IDS_EMITSTOP                    4
#define IDS_AMOUNT                      5
#define IDS_SUBFRAMESAMPLING            6
#define IDS_PF_OPERATOR_CATEGORY        7
#define IDS_OPERATOR_SAMPLEBIRTH_CLASS_NAME 8
#define IDS_TYPEYOURCOMMENTSHERE        8
#define IDS_OPERATOR_SAMPLEBIRTH_OBJECT_NAME 9
#define IDS_VERTEXNOISE                 9
#define IDS_OPERATOR_SAMPLEBIRTH_INTERNAL_NAME 10
#define IDS_SURFACEOFFSETVARIATION      10
#define IDS_SHAPETAPER                  10
#define IDS_OPERATOR_SAMPLEPOSITION_CLASS_NAME 11
#define IDS_RESTRICTTOAXIS              11
#define IDS_OPERATOR_SAMPLEPOSITION_OBJECT_NAME 12
#define IDS_DIVERGENCEAXIS_X            12
#define IDS_OPERATOR_SAMPLEPOSITION_INTERNAL_NAME 13
#define IDS_DIVERGENCEAXIS_Y            13
#define IDS_LOCATION                    14
#define IDS_LOCATIONTYPE_PIVOT          15
#define IDS_LOCATIONTYPE_SURFACE        16
#define IDS_SPEED                       16
#define IDS_LOCATIONTYPE_EDGES          17
#define IDS_RANDOMSEED                  18
#define IDS_OPERATOR_SAMPLESPEED_CLASS_NAME 19
#define IDS_DIVERGENCEAXIS_Z            19
#define IDS_OPERATOR_SAMPLESPEED_OBJECT_NAME 20
#define IDS_OPERATOR_SAMPLESPEED_INTERNAL_NAME 21
#define IDS_ROTATIONF                   22
#define IDS_ATTRACTIONF                 23
#define IDS_OPERATOR_DISPLAY_CLASS_NAME 24
#define IDS_OPERATOR_DISPLAY_OBJECT_NAME 25
#define IDS_OPERATOR_RENDER_CLASS_NAME  26
#define IDS_VIEWPORTTYPE                27
#define IDS_DISPLAYTYPE_NONE            28
#define IDS_DISPLAYTYPE_DOTS            29
#define IDS_DISPLAYTYPE_TICKS           30
#define IDS_DISPLAYTYPE_LINES           31
#define IDS_DISPLAYTYPE_BBOXES          32
#define IDS_DISPLAYTYPE_GEOM            33
#define IDS_VIEWPORTVISIBLE             34
#define IDS_VIEWPORTCOLOR               35
#define IDS_SHOWNUMBERING               36
#define IDS_RENDERTYPE                  37
#define IDS_DISPLAYRENDER               38
#define IDS_RENDERVISIBLE               39
#define IDS_SELECTED                    40
#define IDS_SELECTEDVIEWPORTTYPE        41
#define IDS_SELECTEDRENDERTYPE          42
#define IDS_SELECTEDCOLOR               43
#define IDS_HIDDEN                      44
#define IDS_HIDEBYNUMBERS               45
#define IDS_UNHIDEBYNUMBERS             46
#define IDS_OPERATOR_RENDER_OBJECT_NAME 47
#define IDS_ACTIONLIST_CLASS_NAME       98
#define IDS_ACTIONLIST_OBJECT_NAME      99
#define IDS_ACTIVE                      100
#define IDS_ACTIONS                     101
#define IDS_ACTIVITY                    102
#define IDS_ACTIONLIST_INTERNAL_NAME    103
#define IDS_TEST_DURATION_CLASS_NAME    104
#define IDS_TEST_DURATION_OBJECT_NAME   105
#define IDS_TEST_DURATION_INTERNAL_NAME 106
#define IDS_PF_TEST_CATEGORY            107
#define IDS_TESTTYPE                    108
#define IDS_DURATIONTYPE_TIME           109
#define IDS_DURATIONTYPE_AGE            110
#define IDS_DURATIONTYPE_EVENT          111
#define IDS_CONDITIONTYPE               112
#define IDS_TESTVALUE                   113
#define IDS_VISCOSITY                   114
#define IDS_FIRSTLASTDISPARITY          115
#define IDS_TESTFIRST                   116
#define IDS_TESTLAST                    117
#define IDS_LASTINDEX                   118
#define IDS_ARROW_CLASS_NAME            119
#define IDS_ARROW_OBJECT_NAME           120
#define IDS_ARROW_INTERNAL_NAME         121
#define IDS_ACTIONFROM                  122
#define IDS_ACTIONLISTNEXT              123
#define IDS_PARTICLEGROUP_CLASS_NAME    124
#define IDS_PARTICLEGROUP_OBJECT_NAME   125
#define IDS_PARTICLEGROUP_INTERNAL_NAME 126
#define IDS_PARTICLEGROUPS              127
#define IDS_OPERATOR_SIMPLESHAPE_CLASS_NAME 128
#define IDS_OPERATOR_SIMPLESHAPE_OBJECT_NAME 129
#define IDS_OPERATOR_SIMPLESHAPE_INTERNAL_NAME 130
#define IDS_SHAPETYPE                   131
#define IDS_SHAPETYPE_PYRAMID           132
#define IDS_SHAPETYPE_CUBE              133
#define IDS_SHAPETYPE_SPHERE            134
#define IDS_MESHSIZE                    135
#define IDS_OPERATOR_SIMPLEBIRTH_CLASS_NAME 136
#define IDS_OPERATOR_SIMPLEBIRTH_OBJECT_NAME 137
#define IDS_OPERATOR_SIMPLEBIRTH_INTERNAL_NAME 138
#define IDS_BIRTHTYPE                   139
#define IDS_RATE                        140
#define IDS_ENGINE_CLASS_NAME           141
#define IDS_ENGINE_OBJECT_NAME          142
#define IDS_ENGINE_INTERNAL_NAME        143
#define IDS_OPERATOR_SIMPLEPOSITION_CLASS_NAME 144
#define IDS_OPERATOR_SIMPLEPOSITION_OBJECT_NAME 145
#define IDD_SAMPLEBIRTH_PARAMETERS      146
#define IDS_OPERATOR_SIMPLEPOSITION_INTERNAL_NAME 146
#define IDD_SAMPLEPOSITION_PARAMETERS   147
#define IDS_LOCK                        147
#define IDD_SAMPLESPEED_PARAMETERS      148
#define IDS_INHERIT                     148
#define IDS_DISTINCT                    149
#define IDD_ACTIONLIST_PARAMETERS       150
#define IDS_TOTALDISTINCT               150
#define IDS_LOCATIONTYPE_VERTEX         151
#define IDS_LOCATIONTYPE_EDGE           152
#define IDS_LOCATIONTYPE_VOLUME         153
#define IDS_DISPLAYTYPE_CIRCLES         154
#define IDS_DISPLAYTYPE_DIAMONDS        155
#define IDS_DISPLAYTYPE_BOXES           156
#define IDS_DISPLAYTYPE_ASTERISKS       157
#define IDS_DISPLAYTYPE_TRIANGLES       158
#define IDB_DEPOTICONMASK_OPERATOR      158
#define IDS_OPERATOR_INSTANCESHAPE_CLASS_NAME 159
#define IDS_OPERATOR_INSTANCESHAPE_OBJECT_NAME 160
#define IDS_OPERATOR_INSTANCESHAPE_INTERNAL_NAME 161
#define IDS_SHAPESCALE                  162
#define IDB_DEPOTICONMASK_BIRTH         162
#define IDS_SHAPEVARIATION              163
#define IDB_DEPOTICONMASK_TEST          163
#define IDS_MAPPING                     164
#define IDS_MATERIAL                    165
#define IDS_RANDOMSHAPE                 166
#define IDS_ANIMATEDSHAPE               167
#define IDS_ACQUIRESHAPE                168
#define IDS_SYNCTYPE                    169
#define IDS_SYNCBY_ABSOLUTE             170
#define IDS_SYNCBY_PARTICLE             171
#define IDS_SYNCBY_EVENT                172
#define IDS_SYNCBY_RANDOM               173
#define IDS_RANDOMOFFSET                174
#define IDS_INSTANCETYPE                175
#define IDS_OBJECTASWHOLE               176
#define IDS_OBJECTELEMENTS              177
#define IDS_OBJECTWITHSUBTREE           178
#define IDS_OBJECTANDCHILDREN           179
#define IDS_GROUPASWHOLE                180
#define IDS_GROUPMEMBERS                181
#define IDS_GROUPOBJECT                 182
#define IDS_HIERARCHYOBJECT             183
#define IDS_MESHOBJECT                  184
#define IDS_UNDEFINED                   185
#define IDS_XCOORD                      186
#define IDS_YCOORD                      187
#define IDS_ADDRANDOMOFFSET             188
#define IDB_SIMPLESPEED_INACTIVEICON    188
#define IDS_OPERATOR_FACINGSHAPE_CLASS_NAME 189
#define IDB_SIMPLESPEED_DEPOTICON       189
#define IDS_OPERATOR_FACINGSHAPE_OBJECT_NAME 190
#define IDB_SIMPLESPEED_ACTIVEICON      190
#define IDS_OPERATOR_FACINGSHAPE_INTERNAL_NAME 191
#define IDS_PARALLEL                    192
#define IDS_VIEWPORTTYPE_FRONT          193
#define IDS_VIEWPORTTYPE_BACK           194
#define IDS_VIEWPORTTYPE_TOP            195
#define IDS_VIEWPORTTYPE_BOTTOM         196
#define IDS_VIEWPORTTYPE_LEFT           197
#define IDS_VIEWPORTTYPE_RIGHT          198
#define IDS_SIZESPACE                   199
#define IDS_UNITS                       200
#define IDS_PROPORTION                  201
#define IDS_SIZEVARIATION               202
#define IDS_PIVOTAT                     203
#define IDS_PIVOTAT_TOP                 204
#define IDS_PIVOTAT_CENTER              205
#define IDS_PIVOTAT_BOTTOM              206
#define IDS_WHRATIO                     207
#define IDS_NUMFSUBMTLS                 208
#define IDS_LOOP                        209
#define IDS_SUBSPERFRAME                210
#define IDS_OPERATOR_SIMPLESPEED_CLASS_NAME 211
#define IDS_OPERATOR_SIMPLESPEED_OBJECT_NAME 212
#define IDS_OPERATOR_SIMPLESPEED_INTERNAL_NAME 213
#define IDS_DIFFUSION                   214
#define IDS_DIRECTION                   215
#define IDS_ALONG_ICON_ARROW            215
#define IDS_ICON_CENTER_0UT             216
#define IDS_ICON_ARROW_OUT              217
#define IDS_RAND_3D                     218
#define IDS_RAND_HORIZ                  219
#define IDS_INHERIT_PREV                220
#define IDB_SPEEDAVOIDCOLLISION_DEPOTICON 220
#define IDB_SPEEDAVOIDCOLLISIONS_DEPOTICON 220
#define IDS_REVERSE                     221
#define IDB_SPEEDAVOIDCOLLISION_INACTIVEICON 221
#define IDB_SPEEDAVOIDCOLLISIONS_INACTIVEICON 221
#define IDS_DIVERGENCE                  222
#define IDB_SPEEDAVOIDCOLLISION_ACTIVEICON 222
#define IDB_SPEEDAVOIDCOLLISIONS_ACTIVEICON 222
#define IDS_WORLD                       223
#define IDS_EULER                       224
#define IDD_DLG_INSTANCESHAPETYPE       225
#define IDS_EULER_X                     225
#define IDS_EULER_Y                     226
#define IDB_SPEEDFOLLOWLEADER_DEPOTICON 226
#define IDD_SIMPLESPEED_PARAMETERS      227
#define IDS_EULER_Z                     227
#define IDB_SPEEDFOLLOWLEADER_INACTIVEICON 227
#define IDD_FluidTEST_PARAMETERS        227
#define IDS_INHERITEDSCALE              228
#define IDB_SPEEDFOLLOWLEADER_ACTIVEICON 228
#define IDS_USEMATERIAL                 229
#define IDS_OPERATOR_SIMPLEORIENTATION_CLASS_NAME 230
#define IDS_OPERATOR_SIMPLEORIENTATION_OBJECT_NAME 231
#define IDD_COMPLEXSPEED_PARAMETERS     232
#define IDS_OPERATOR_SIMPLEORIENTATION_INTERNAL_NAME 232
#define IDS_OPERATOR_MARKSHAPE_CLASS_NAME 233
#define IDS_OPERATOR_MARKSHAPE_OBJECT_NAME 234
#define IDS_OPERATOR_MARKSHAPE_INTERNAL_NAME 235
#define IDS_CONTACTOBJECT               236
#define IDS_PICKCONTACTOBJECT           237
#define IDS_SURFACEAMINATION            238
#define IDS_ALIGNTO                     239
#define IDS_ALIGNTO_SPEED               240
#define IDS_ALIGNTO_PARTICLEX           241
#define IDS_ALIGNTO_PARTICLEY           242
#define IDS_ALIGNTO_PARTICLEZ           243
#define IDS_ALIGNTO_RANDOM              244
#define IDS_WIDTH                       245
#define IDS_LENGTH                      246
#define IDS_ANGLEDISTORTION             247
#define IDS_MAXDISTORTION               248
#define IDS_MARKTYPE                    249
#define IDS_HEIGHT                      250
#define IDS_MULTIELEMENTS               251
#define IDS_PIVOTOFFSET                 252
#define IDS_SURFACEOFFSET               253
#define IDS_UPDATESCHEMATICS            254
#define IDS_SPINRATE                    255
#define IDS_WORLD_SPACE                 256
#define IDS_PARTICLE_SPACE              257
#define IDS_SPEED_SPACE                 258
#define IDS_SPIN_X                      259
#define IDS_SPIN_Y                      260
#define IDS_SPIN_Z                      261
#define IDS_PW_FORCENODE                262
#define IDS_PW_INFLUENCE                263
#define IDS_PW_SYNC                     264
#define IDS_PW_ABSOLUTE                 265
#define IDS_PW_PARTICLEAGE              266
#define IDS_PW_EVENTDURATION            267
#define IDS_OPERATOR_FORCESPACEWARP_CLASS_NAME 268
#define IDS_OPERATOR_FORCESPACEWARP_OBJECT_NAME 269
#define IDS_TESTDURATION_DESCRIPTION    270
#define IDS_OPERATOR_SIMPLESPIN_CLASS_NAME 271
#define IDS_OPERATOR_SIMPLESPIN_OBJECT_NAME 272
#define IDS_OPERATOR_SIMPLESPIN_INTERNAL_NAME 273
#define IDS_TEST_COLLISIONSPACEWARP_CLASS_NAME 273
#define IDS_OPERATOR_FACINGSHAPE_DESCRIPTION 274
#define IDS_OPERATOR_FORCESW_DESCRIPTION 275
#define IDS_OPERATOR_INSTANCESHAPE_DESCRIPTION 276
#define IDS_OPERATOR_MARKSHAPE_DESCRIPTION 277
#define IDS_OPERATOR_DISPLAY_DESCRIPTION 278
#define IDS_OPERATOR_SIMPLEBIRTH_DESCRIPTION 279
#define IDS_OPERATOR_SIMPLESPEED_DESCRIPTION 280
#define IDS_OPERATOR_SIMPLEPOSITION_DESCRIPTION 281
#define IDS_OPERATOR_SIMPLESPIN_DESCRIPTION 282
#define IDS_ACTIONLISTWIDTH             283
#define IDS_TESTSPAWN_DESCRIPTION       284
#define IDS_TESTSPAWNONCOLLISION_DESCRIPTION 285
#define IDS_SPAWNTYPE                   286
#define IDS_DELETEPARENT                287
#define IDS_SPAWNRATE                   288
#define IDS_SPAWNSTEPSIZE               289
#define IDS_SPAWNABLE                   290
#define IDS_OFFSPRINGSNUM               291
#define IDS_RESTARTAGE                  292
#define IDS_SPEEDTYPE                   293
#define IDS_SPEEDINHERITED              294
#define IDS_SCALE                       295
#define IDS_TESTCOLLISIONSPACEWARP_DESCRIPTION 296
#define IDS_TEST_COLLISIONSPACEWARP_OBJECT_NAME 297
#define IDS_NUMCOLLISIONS               298
#define IDS_PARENTSPEED                 299
#define IDS_OFFSPRINGSPEED              300
#define IDS_SPEEDTYPE_BOUNCE            301
#define IDS_SPEEDTYPE_CONTINUE          302
#define IDS_SPEEDTYPE_STOP              303
#define IDS_SPEEDTYPE_RANDOM            304
#define IDS_SPEEDTYPE_TANGENT           305
#define IDS_TEST_SPAWN_CLASS_NAME       306
#define IDS_TEST_SPAWN_OBJECT_NAME      307
#define IDS_TEST_SPAWNONCOLLISION_CLASS_NAME 308
#define IDS_TEST_SPAWNONCOLLISION_OBJECT_NAME 309
#define IDS_OPERATOR_EXIT_CLASS_NAME    310
#define IDS_OPERATOR_EXIT_OBJECT_NAME   311
#define IDS_OPERATOR_EXIT_DESCRIPTION   312
#define IDS_EXITTYPE                    313
#define IDS_LIFESPAN                    314
#define IDS_TEST_COLLISIONSPACEWARP_NODE 315
#define IDS_PW_COLLISIONTESTTYPE        316
#define IDS_PW_COLLISIONSPEEDOPTION     317
#define IDS_PW_COLLISIONONCE            318
#define IDS_OPERATOR_RENDER_DESCRIPTION 318
#define IDS_PW_COLLISIONCONTINUE        319
#define IDS_PW_COLLISIONSTOP            320
#define IDS_PW_COLLISIONRANDOM          321
#define IDS_PW_MINSPEED                 322
#define IDS_PW_MAXSPEED                 323
#define IDS_PW_WILLCOLLIDEFRAME         324
#define IDS_PW_COLLISIONCOUNT           325
#define IDS_PW_COLLISIONCOUNTOPTIONS    326
#define IDS_PARTICLE                    327
#define IDS_SELECTIONLEVEL              328
#define IDS_GENERATESELECTIONCHANNEL    329
#define IDS_SPEED_SPACE_FOLLOW          330
#define IDS_NEWRANDOMSEED               331
#define IDS_PICKOBJECT                  332
#define IDS_PICKSPLINE                  332
#define IDS_PICKCAMERA                  333
#define IDS_TEST_COLLISIONSPACEWARP_NODES 334
#define IDD_SCRIPTBIRTH_PARAMETERS      423
#define IDD_SCRIPTACTION_PARAMETERS     424
#define IDD_MATERIAL_PARAMETERS         425
#define IDS_MASS                        426
#define IDS_TEMPER                        426
#define IDD_SPEEDFOLLOWLEADER_PARAMETERS 430
#define IDD_SPEEDAVOIDCOLLISIONS_PARAMETERS 431
#define IDC_LOCATIONTEXT                1000
#define IDC_NAMETEXT                    1000
#define IDC_SPEEDTEXT                   1001
#define IDC_SPEED                       1003
#define IDC_PARTICLETEXT                1003
#define IDC_SPEEDSPIN                   1004
#define IDC_LOCATION                    1005
#define IDC_VARIANCESPIN                1006
#define IDC_USESCRIPTFILE               1009
#define IDC_TESTLASTTEXT                1014
#define IDC_LASTINDEXTEXT               1015
#define IDC_HIDDENLIST                  1016
#define IDC_OFFSETMAXTEXT2              1017
#define IDC_LASTINDEXTEXT2              1018
#define IDC_SELECTEDRENDER              1020
#define IDC_ACTIVATE                    1020
#define IDC_OBJECTFRAME2                1021
#define IDC_TYPE2                       1022
#define IDC_TYPE3                       1023
#define IDC_VISCOSITY                   1024
#define IDC_VISCOSITYSPIN               1025
#define IDC_DIFFUSION                   1026
#define IDC_DIFFUSIONSPIN               1027
#define IDC_MASS                        1028
#define IDC_MASSSPIN                    1029
#define IDC_TEMPER                      1031
#define IDC_TEMPERSPIN                  1032
#define IDC_VISCOSITYTEXT               1035
#define IDC_DIFFUSIONTEXT               1036
#define IDC_MASSTEXT                    1037
#define IDC_UNIQUENESSBOX               1038
#define IDC_SEEDTEXT                    1039
#define IDC_SEED                        1040
#define IDC_SEEDSPIN                    1041
#define IDC_NEW                         1042
#define IDC_CLEANSIM                    1043
#define IDC_TEMPERTEXT                  1044
#define IDC_STOPDISTANCETEXT            1045
#define IDC_REVERSE                     1056
#define IDC_APPLYONCE                   1059
#define IDC_APPLYCONSTANTLY             1061
#define IDC_INFLUENCETEXT2              1062
#define IDC_USESTOPDISTANCE             1065
#define IDC_USESTEERINGLIMIT            1066
#define IDC_INFLUENCE2                  1067
#define IDC_ZTEXT2                      1067
#define IDC_INFLUENCESPIN2              1068
#define IDC_Z2                          1068
#define IDC_FSWFRAME                    1072
#define IDC_ZSPIN2                      1072
#define IDC_X2                          1074
#define IDC_CAMERAOBJECT                1075
#define IDC_XSPIN2                      1075
#define IDC_VIEWPORT                    1076
#define IDC_MIDDLETEXT                  1076
#define IDC_Y3                          1077
#define IDC_INUNITS                     1078
#define IDC_YSPIN3                      1078
#define IDC_INDEGREES                   1079
#define IDC_Z3                          1080
#define IDC_FIELDS                      1081
#define IDC_USEMATERIAL                 1081
#define IDC_ZSPIN3                      1081
#define IDC_MATERIALFRAME               1082
#define IDC_CAMERAOBJECTNAME            1083
#define IDC_DEGREES                     1084
#define IDC_DEGREESSPIN                 1085
#define IDC_TYPE_LIST                   1091
#define IDC_DIVERGENCETEXT              1105
#define IDC_DIVERGENCE                  1106
#define IDC_DIVERGENCESPIN              1107
#define IDC_INHERITED_PRCT              1120
#define IDC_VARIATION_PRCT              1121
#define IDC_SWITCHFRAME                 1124
#define IDC_AFFECTS_PRCT                1131
#define IDC_INFLUENCE_PRCT              1132
#define IDC_AMOUNTVARIATION_PRCT        1132
#define IDC_SCALE_PRCT                  1135
#define IDC_SCALEVARIATION_PRCT         1136
#define IDC_OBJECTANDCHILDREN           1142
#define IDC_OBJECTWHOLE                 1143
#define IDC_OBJECTELEMENTS              1144
#define IDC_FRTEXT                      1144
#define IDC_VARFRTEXT                   1147
#define IDC_RESTRARTAGE                 1147
#define IDC_GENSELECT                   1149
#define IDS_TRUEFORPARTICLESCOLLIDED    1150
#define IDS_TRUEFORSPAWNPARTICLES       1151
#define IDS_PARTICLEFLOW_CATEGORY       1152
#define IDS_UMAP                        1161
#define IDC_PERCENT                     1162
#define IDS_VMAP                        1162
#define IDS_WMAP                        1163
#define IDC_STATICID                    1164
#define IDS_ASSIGNMATERIAL              1164
#define IDC_DYNAMICID                   1165
#define IDS_ASSIGNMATERIALID            1165
#define IDS_MTLIDTYPE                   1166
#define IDS_IDANIMTYPE                  1167
#define IDS_NUMSUBMTLS                  1168
#define IDS_MATERIALID                  1169
#define IDS_SUBMTLRATE                  1170
#define IDS_MTLID1FREQ                  1171
#define IDS_MTLID2FREQ                  1172
#define IDS_MTLID3FREQ                  1173
#define IDS_MTLID4FREQ                  1174
#define IDS_MTLID5FREQ                  1175
#define IDS_MTLID6FREQ                  1176
#define IDS_MTLID7FREQ                  1177
#define IDS_MTLID8FREQ                  1178
#define IDS_RATEPERFRAME                1179
#define IDS_RATEPERPARTICLE             1180
#define IDS_CHANNELTYPE                 1181
#define IDS_MAPCHANNEL                  1182
#define IDS_SHOWINVIEWPORT              1183
#define IDS_OPERATOR_POSITIONONOBJECT_CLASS_NAME 1184
#define IDS_OPERATOR_POSITIONONOBJECT_OBJECT_NAME 1185
#define IDS_OPERATOR_POSITIONONOBJECT_DESCRIPTION 1186
#define IDS_OPERATOR_EMITTER_NODES      1187
#define IDS_USESURFACEOFFSET            1188
#define IDC_PICKNODE2                   1189
#define IDS_SURFACEOFFSETMINIMUM        1189
#define IDC_PICK                        1189
#define IDC_AFTERLASTTEXT               1190
#define IDS_SURFACEOFFSETMAXIMUM        1190
#define IDC_BYDIRECTION                 1191
#define IDS_USENONUNIFORMDENSITY        1191
#define IDC_BYBITMAP                    1192
#define IDS_NONUNIFORMTYPE              1192
#define IDS_ATTEMPTSMAX                 1193
#define IDS_APARTPLACEMENT              1194
#define IDC_PARTICLEID                  1194
#define IDS_DISTINCTPOINTSONLY          1195
#define IDS_APARTDISTANCE               1196
#define IDS_DENSITYTYPE                 1197
#define IDS_USESUBMTL                   1198
#define IDS_DENSITYTYPE_GRAYSCALE       1199
#define IDS_DENSITYTYPE_OPACITY         1200
#define IDS_DENSITYTYPE_GRAYSCALEOPACITY 1201
#define IDS_DENSITYTYPE_RED             1202
#define IDS_DENSITYTYPE_GREEN           1203
#define IDS_DENSITYTYPE_BLUE            1204
#define IDS_OPERATOR_SPEEDSURFACENORMALS_CLASS_NAME 1205
#define IDC_TARGETOBJECT                1205
#define IDS_OPERATOR_SPEEDSURFACENORMALS_OBJECT_NAME 1206
#define IDS_OPERATOR_SPEEDSURFACENORMALS_DESCRIPTION 1207
#define IDC_USEDOCKINGDIRECTION         1207
#define IDS_OPERATOR_SPEEDFOLLOWLEADER_CLASS_NAME 1208
#define IDS_OPERATOR_MATERIALDYNAMIC_CLASS_NAME 1208
#define IDS_OPERATOR_SPEEDFOLLOWLEADER_OBJECT_NAME 1209
#define IDS_OPERATOR_MATERIALDYNAMIC_OBJECT_NAME 1209
#define IDC_VIEWPORTTYPE                1210
#define IDS_OPERATOR_SPEEDFOLLOWLEADER_DESCRIPTION 1210
#define IDS_OPERATOR_MATERIALDYNAMIC_DESCRIPTION 1210
#define IDS_OPERATOR_SPEEDAVOIDCOLLISIONS_CLASS_NAME 1211
#define IDS_OPERATOR_MATERIALFREQUENCY_CLASS_NAME 1211
#define IDS_OPERATOR_SPEEDAVOIDCOLLISIONS_OBJECT_NAME 1212
#define IDS_OPERATOR_MATERIALFREQUENCY_OBJECT_NAME 1212
#define IDS_OPERATOR_SPEEDAVOIDCOLLISIONS_DESCRIPTION 1213
#define IDS_OPERATOR_MATERIALFREQUENCY_DESCRIPTION 1213
#define IDS_OPERATOR_SPEEDCOPY_CLASS_NAME 1214
#define IDC_LEADERFRAME                 1214
#define IDS_OPERATOR_SPEEDCOPY_OBJECT_NAME 1215
#define IDC_FOLLOWFRAME                 1215
#define IDS_OPERATOR_SPEEDCOPY_DESCRIPTION 1216
#define IDC_SPEEDLIMITEXT               1216
#define IDS_OPERATOR_SPEEDKEEPAPART_CLASS_NAME 1217
#define IDC_ICONTYPE                    1217
#define IDS_OPERATOR_SPEEDKEEPAPART_OBJECT_NAME 1218
#define IDC_OBSTACLESFRAME              1218
#define IDS_OPERATOR_SPEEDKEEPAPART_DESCRIPTION 1219
#define IDC_OBSTACLEOBJECTS             1219
#define IDS_TEST_SPEEDGOTOTARGET_CLASS_NAME 1220
#define IDC_OBSTACLEICON                1220
#define IDS_TEST_SPEEDGOTOTARGET_OBJECT_NAME 1221
#define IDC_AVOIDANCEFRAME              1221
#define IDS_TEST_SPEEDGOTOTARGET_DESCRIPTION 1222
#define IDC_AVOIDANCETYPE               1222
#define IDC_STEERINGLIMITEXT            1223
#define IDS_SPEEDTYPE_ONCE              1223
#define IDC_ALERTFRAME                  1224
#define IDS_SPEEDTYPE_CONTINUOUS        1224
#define IDC_SYNCOFFSETTEXT              1225
#define IDC_ALERTTYPE                   1225
#define IDS_SETSPEEDMAGNITUDE           1225
#define IDC_SYNCFRAMETEXT               1226
#define IDC_TIMETEXT                    1226
#define IDS_SPEEDVALUE                  1226
#define IDC_TIME                        1227
#define IDS_SPEEDVARIATION              1227
#define IDC_TIMESPIN                    1228
#define IDS_SURFACEOBJECTS              1228
#define IDC_GROUPWHOLE                  1229
#define IDS_SETSPEEDBYSURFACEMTL        1229
#define IDS_MATERIALTYPE                1230
#define IDC_OBJECTWITHSUBTREE           1231
#define IDS_MATERIALTYPE_GRAYSCALE      1231
#define IDS_MATERIALTYPE_RGBASWORLD     1232
#define IDC_STOPDISTANCE                1233
#define IDS_MATERIALTYPE_RGBASLOCAL     1233
#define IDC_STOPDISTANCESPIN            1234
#define IDS_DIRECTIONTYPE_NORMALS       1234
#define IDC_STEERINGLIMIT               1235
#define IDS_DIRECTIONTYPE_OUTOFSURFACE  1235
#define IDC_STEERINGLIMITSPIN           1236
#define IDS_DIRECTIONTYPE_PARALLEL      1236
#define IDS_ACCELERATIONLIMIT           1237
#define IDS_UNLIMITEDRANGE              1238
#define IDS_RANGE                       1239
#define IDS_FALLOFF                     1240
#define IDS_DIRECTIONTYPE               1241
#define IDS_SPEEDTYPE_BYSPEED           1242
#define IDS_SPEEDTYPE_BYTIME            1243
#define IDS_CRUISESPEED                 1244
#define IDS_TIMINGTYPE                  1245
#define IDS_TIME                        1246
#define IDS_TIMEVARIATION               1247
#define IDS_USEDOCKINGSPEED             1248
#define IDS_DOCKINGSPEED                1249
#define IDS_DOCKINGEASYIN               1250
#define IDS_TARGETTYPE                  1251
#define IDS_TARGETOBJECTS               1252
#define IDS_ASSIGNMENTTYPE              1253
#define IDS_ASSIGNMENT_RANDOM           1254
#define IDS_ASSIGNMENT_DISTANCE         1255
#define IDS_ASSIGNMENT_STEERING         1256
#define IDS_ASSIGNMENT_INTEGER          1257
#define IDS_USEDOCKINGDIRECTION         1258
#define IDS_DOCKINGTYPE                 1259
#define IDS_DOCKINGTYPE_PARALLEL        1260
#define IDS_DOCKINGTYPE_SPHERICAL       1261
#define IDS_DOCKINGTYPE_CYLINDRICAL     1262
#define IDS_ICONSIZE                    1263
#define IDS_DOCKINGTYPE_NORMAL          1264
#define IDS_SHAPETYPE_VERTEX            1265
#define IDS_SPEEDTYPE_SPEEDTHENTIME     1266
#define IDS_SPEEDTYPE_NOCONTROL         1266
#define IDS_USECRUISESPEED              1267
#define IDS_CRUISESPEEDVARIATION        1268
#define IDS_DOCKINGSPEEDVARIATION       1269
#define IDS_SWITCHDISTANCE              1270
#define IDS_TESTDISTANCE                1270
#define IDS_FOLLOWTARGET                1271
#define IDS_DOCKINGTYPE_NONE            1272
#define IDS_LOCKONTARGET                1273
#define IDS_ASSIGNMENT_SURFACE          1274
#define IDS_ASSIGMENT_DEVIATION         1275
#define IDS_AIMPOINTTYPE                1276
#define IDS_AIMPOINT_RANDOM             1277
#define IDS_AIMPOINT_SURFACE            1278
#define IDC_MULTIPLIERPCNT              1278
#define IDS_AIMPOINT_VECTOR             1279
#define IDC_VARIATIONPCNT               1279
#define IDS_FORCE                       1280
#define IDS_RANGETYPE                   1281
#define IDS_CORESIZE                    1282
#define IDS_FALLOFFSIZE                 1283
#define IDS_CORERATIO                   1284
#define IDS_FALLOFFRATIO                1285
#define IDS_SELECTEDGROUPS              1286
#define IDS_SELECTEDSYSTEMS             1287
#define IDS_SCOPETYPE                   1288
#define IDS_PARAMETERCHANGE             1289
#define IDS_USEACCELLIMIT               1290
#define IDS_USESPEEDLIMIT               1291
#define IDS_ACCELLIMIT                  1292
#define IDS_SPEEDLIMIT                  1293
#define IDS_USESPEEDVARIATION           1294
#define IDS_SPEEDMIN                    1295
#define IDS_SPEEDMAX                    1296
#define IDS_STEERTOWARDSTRAJECTORY      1297
#define IDS_DISTANCE                    1298
#define IDS_USEORIENT                   1299
#define IDS_INFLUENCE                   1300
#define IDS_TEST_GOTONEXTEVENT_CLASS_NAME 1301
#define IDS_TEST_GOTONEXTEVENT_OBJECT_NAME 1302
#define IDS_TEST_GOTONEXTEVENT_DESCRIPTION 1303
#define IDS_OPERATOR_COMMENTS_CLASS_NAME 1304
#define IDS_OPERATOR_COMMENTS_OBJECT_NAME 1305
#define IDS_OPERATOR_COMMENTS_DESCRIPTION 1306
#define IDS_COMMENTS                    1307
#define IDS_OPERATOR_SIMPLESCALE_CLASS_NAME 1308
#define IDS_OPERATOR_SIMPLESCALE_OBJECT_NAME 1309
#define IDS_OPERATOR_SIMPLESCALE_DESCRIPTION 1310
#define IDS_TYPE                        1311
#define IDS_OVERWRITE_ONCE              1312
#define IDS_INHERIT_ONCE                1313
#define IDS_ABSOLUTE                    1314
#define IDS_RELATIVE_FIRST              1315
#define IDS_RELATIVE_SUCCESSIVE         1316
#define IDS_XSCALE_FACTOR               1317
#define IDS_YSCALE_FACTOR               1318
#define IDS_ZSCALE_FACTOR               1319
#define IDS_CONSTRAINSCALE              1320
#define IDS_XSCALE_VARIATION            1321
#define IDS_YSCALE_VARIATION            1322
#define IDS_ZSCALE_VARIATION            1323
#define IDS_BIAS                        1324
#define IDS_NONE                        1325
#define IDS_CENTERED                    1326
#define IDS_TOWARDSMIN                  1327
#define IDS_TOWARDSMAX                  1328
#define IDS_CONSTRAINVARIATION          1329
#define IDS_MULTIPLIER                  1330
#define IDS_FORCESPACEWARP_NODES        1331
#define IDS_FORCEOVERLAPPING            1332
#define IDS_RATIO                       1333
#define IDS_SELECTEDSOURCES             1334
#define IDS_EVERYNTH                    1335
#define IDS_FIRSTN                      1336
#define IDS_PEREMISSIONSOURCE           1337
#define IDC_BUTTON1                     1337
#define IDS_TEST_SPLITBYAMOUNT_CLASS_NAME 1338
#define IDS_TEST_SPLITBYAMOUNT_OBJECT_NAME 1339
#define IDS_TESTSPLITBYAMOUNT_DESCRIPTION 1340
#define IDS_TEST_SPLITBYSOURCE_CLASS_NAME 1341
#define IDS_TEST_SPLITBYSOURCE_OBJECT_NAME 1342
#define IDS_TESTSPLITBYSOURCE_DESCRIPTION 1343
#define IDS_TEST_SPLITSELECTED_CLASS_NAME 1344
#define IDS_TEST_SPLITSELECTED_OBJECT_NAME 1345
#define IDS_TESTSPLITSELECTED_DESCRIPTION 1346
#define IDS_LOCATIONTYPE_SELVERTEX      1347
#define IDS_LOCATIONTYPE_SELEDGE        1348
#define IDS_LOCATIONTYPE_SELFACES       1349
#define IDS_SCRIPTWIRING                1350
#define IDS_USESCRIPTWIRING             1351
#define IDS_USESCRIPTFLOAT              1352
#define IDS_USESCRIPTINTEGER            1353
#define IDS_USESCRIPTVECTOR             1354
#define IDS_USESCRIPTMATRIX             1355
#define IDS_TEST_SPEEDGOTOTARGET_PVIEW_NAME 1356
#define IDS_OPERATOR_SPEEDCOPY_PVIEW_NAME 1357
#define IDS_RESETPARTICLEAGE            1358
#define IDS_VISIBLE                     1359
#define IDS_COLOR                       1360
#define IDS_SELECTEDTYPE                1361
#define IDS_ALIGNTOHORIZON              1362
#define IDS_ALIGNTOSPEEDFOLLOW          1363
#define IDS_RANDOM                      1364
#define IDS_ALLOWSPIN                   1365
#define IDS_ORIENTATION                 1366
#define IDS_MTLID9FREQ                  1367
#define IDS_MTLID10FREQ                 1368
#define IDS_RATETYPE                    1369
#define IDS_RATEPERSECOND               1370
#define IDS_RANDOMIZEAGE                1371
#define IDS_MAXAGEOFFSET                1372
#define IDS_MESHUSESCALE                1373
#define IDS_MESHSCALE                   1374
#define IDS_TEST_GOTOROTATION_CLASS_NAME 1375
#define IDS_TEST_GOTOROTATION_OBJECT_NAME 1376
#define IDS_SENDOUT                     1377
#define IDS_TRANSITIONTYPE              1378
#define IDS_TARGETROTATION              1379
#define IDS_STOPSPINNING                1380
#define IDS_AGE                         1381
#define IDS_DURATION                    1382
#define IDS_TESTGOTOROTATION_DESCRIPTION 1383
#define IDS_MATCHINITIALSPIN            1384
#define IDS_SPINVARIATION               1385
#define IDS_EASEIN                      1386
#define IDS_ABSOLUTE_ABBR               1387
#define IDS_EVENT                       1388
#define IDS_PICKGEOMETRYOBJECT          1389
#define IDS_PICKCAMERAOROBJECT          1390
#define IDS_TOTAL_ABBR                  1391
#define IDS_ALL                         1392
#define IDS_BYAGE                       1393
#define IDS_GROUP                       1394
#define IDS_SYSTEM                      1395
#define IDS_SELECTEDGROUPS_ABBR         1396
#define IDS_SELECTEDSYSTEMS_ABBR        1397
#define IDS_ONCE                        1398
#define IDS_BYRATE                      1399
#define IDS_BYTRAVEL                    1400
#define IDS_SPEEDTHENTIME               1401
#define IDS_TH_LikeInNth                1402
#define IDS_FIRST                       1403
#define IDS_AFTER                       1404
#define IDS_FRACTION                    1405
#define IDS_EVERY                       1406
#define IDS_ST_LikeIn1st                1407
#define IDS_ND_LikeIn2nd                1408
#define IDS_RD_LikeIn3rd                1409
#define IDS_AT                          1410
#define IDS_SELECTFORCESPACEWARPS       1411
#define IDS_SELECT                      1412
#define IDS_SELECTEMITTEROBJECTS        1413
#define IDS_SELECTSURFACEOBJECTS        1414
#define IDS_SELECTTARGETOBJECTS         1415
#define IDS_SELECTDEFLECTORS            1416
#define IDS_SPLITTYPE                   1417
#define IDS_MESHCOUNT                   1418
#define IDS_PARTICLESPERMESH            1419
#define IDS_TEST_SCALE_CLASS_NAME       1420
#define IDS_TEST_SCALE_OBJECT_NAME      1421
#define IDS_PRESIZE                     1422
#define IDS_POSTSIZE                    1423
#define IDS_SCALETYPE_PRESIZE           1424
#define IDS_SCALETYPE_POSTSIZE          1425
#define IDS_SCALETYPE_SCALE             1426
#define IDS_AXISTYPE                    1427
#define IDS_AXISTYPE_AVERAGE            1428
#define IDS_AXISTYPE_MINIMUM            1429
#define IDS_AXISTYPE_MEDIAN             1430
#define IDS_AXISTYPE_MAXIMUM            1431
#define IDS_AXISTYPE_X                  1432
#define IDS_AXISTYPE_Y                  1433
#define IDS_AXISTYPE_Z                  1434
#define IDS_SIZEVALUE                   1435
#define IDS_SCALEVALUE                  1436
#define IDS_SCALEVARIATION              1437
#define IDS_TESTSCALE_DESCRIPTION       1438
#define IDS_TEST_SPEED_CLASS_NAME       1439
#define IDS_TEST_SPEED_OBJECT_NAME      1440
#define IDS_SPEEDX                      1441
#define IDS_SPEEDY                      1442
#define IDS_SPEEDZ                      1443
#define IDS_ACCELERATION_ABBR           1444
#define IDS_ACCELERATIONX_ABBR          1445
#define IDS_ACCELERATIONY_ABBR          1446
#define IDS_ACCELERATIONZ_ABBR          1447
#define IDS_STEERING                    1448
#define IDS_SPEEDTYPE_SPEEDMAG          1449
#define IDS_SPEEDTYPE_SPEEDX            1450
#define IDS_SPEEDTYPE_SPEEDY            1451
#define IDS_SPEEDTYPE_SPEEDZ            1452
#define IDS_SPEEDTYPE_ACCELMAG          1453
#define IDS_SPEEDTYPE_ACCELX            1454
#define IDS_SPEEDTYPE_ACCELY            1455
#define IDS_SPEEDTYPE_ACCELZ            1456
#define IDS_SPEEDTYPE_STEERINGRATE      1457
#define IDS_UNITVALUE                   1458
#define IDS_UNITVARIATION               1459
#define IDS_ANGLEVALUE                  1460
#define IDS_ANGLEVARIATION              1461
#define IDS_TESTSPEED_DESCRIPTION       1462
#define IDS_SPEEDTYPE_WHENACCELS        1463
#define IDS_SPEEDTYPE_WHENSLOWS         1464
#define IDS_IFACCELERATES_ABBR          1465
#define IDS_IFDECELERATES_ABBR          1466
#define IDS_CONTINUOUSUPDATE            1467
#define IDS_GENERATEMAPPINGCOORDS       1468
#define IDS_SPEED_FOLLOW                1469
#define IDS_TESTTYPE_TARGETPIVOT        1470
#define IDS_TESTTYPE_TARGETPOINT        1471
#define IDS_TARGETSYNCTYPE              1473
#define IDS_NOCONTROL                   1474
#define IDS_DOCKINGDISTANCE             1475
#define IDS_COLORTYPE                   1479
#define IDS_OPERATOR_SIMPLESHAPE_PVIEW_NAME 1480
#define IDS_OPERATOR_EXIT_PVIEW_NAME    1481
#define IDS_OPERATOR_SIMPLESCALE_PVIEW_NAME 1482
#define IDS_OPERATOR_DISPLAY_PVIEW_NAME 1483
#define IDS_OPERATOR_RENDER_PVIEW_NAME  1484
#define IDS_DELETE                      1485
#define IDS_SETSCALE                    1486
#define IDS_MATERIALTYPE_LUMCENTER      1487
#define IDS_DISPLAYTYPE_PHANTOM         1488
#define IDS_ASSIGNEDMATERIAL            1489
#define IDS_NOTHING                     1490
#define IDS_LOOKATOBJECT                1491
#define IDS_SHAPEOBJECT                 1492
#define IDC_DIRECTION                   1500
#define IDC_SELECT                      3027
#define IDC_SELECTNUMBERS               3028
#define IDC_HIDESELECTED                3029
#define IDC_HIDEUNSELECTED              3030
#define IDC_HIDEBYHIT                   3031
#define IDC_HIDEBYNUMBERS               3032
#define IDC_UNHIDEALL                   3033
#define IDC_UNHIDEBYNUMBERS             3034
#define IDC_SELECTEDCOLOR               3035
#define IDC_HIDEEDIT                    3037
#define IDC_UNHIDEEDIT                  3038
#define IDS_PLUS_OR_MINUS_CHAR          3039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        282
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1338
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
